### PR TITLE
Update to newest Mupen64-Next core.

### PR DESCRIPTION
**Pull request by mudlord**

### CODE REVIEW

**Comment by ghost** [comment]
Can't wait to test this core out once this pullrequest is merged, paraLLeXT seems to be the N64 core in Libretro I'm looking for.

Awesome work @mudlord

**Comment by mudlord** [comment]
Well it has a huge amount of work to go. Currently GLideN64 needs to be merged as well as fixes to its state machine, which seems to be causing a few framebuffer object issues compared to standalone.

**Comment by Tatsuya79** [comment]
VI overlay option is always on "AA only" right now, just like if set_vi_dedither and blur weren't set and so being false.
Other options could be not set as well.

retroarch.exe stays active after quitting RA using parallelXT.

After closing the core in RA the gamepad directions stop responding, only A and B work.

win7 x64

**Comment by Tatsuya79** [comment]
Build fails: https://pastebin.com/ewx9NsHY

**Comment by mudlord** [comment]
lol ye, should have checked.

**Pull request merged**
